[release]
product = "ironbed"
authority = "https://releases.ironbed.perish.uk"
binaries = ["ironbed"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[release.cargo]
registry = "perish"
packages = ["ironbed-proto"]
