[release]
product = "ironbed"
authority = "https://releases.ironbed.perish.uk"
binaries = ["ironbed"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[release.cargo]
registry = "perish"
packages = ["ironbed-proto"]

[[document]]
strategy = "agent"
source = [{ path = ".", seal = "550da35123ccac933b7be3be3337fa5ca7fabf705f447cbd4025d096e0b18219" }]
target-seal = "dd31fcfa6d62fba145491719175752b7eb2c659ccb882ccd04d26487cf0a0384"

[[document]]
strategy = "architecture"
source = [{ path = ".", seal = "550da35123ccac933b7be3be3337fa5ca7fabf705f447cbd4025d096e0b18219" }]
target-seal = "f88e6cf83eeaf0a7b99a2ee3daf4966044685a71194839af2ee9927f1b1cbe1d"
